services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: dcguser
      POSTGRES_PASSWORD: dcgpassword
      POSTGRES_DB: dcgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: